import { Inter } from 'next/font/google'
import './globals.css'
import SearchField from '../components/SearchField';
import EditButton from '../components/EditButton';
import { Suspense } from 'react';
import NoteListSkeleton from '../components/NoteListSkeleton';
import NoteList from '../components/NoteList';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="main">
          <section className="col sidebar">
            <section className="sidebar-header">
              <img
                className="logo"
                src="/logo.svg"
                width="22px"
                height="20px"
                alt=""
                role="presentation"
              />
              <strong>React Notes</strong>
            </section>
            <section className="sidebar-menu" role="menubar">
              <SearchField />
              <EditButton noteId={null}>New</EditButton>
            </section>
            <nav>
              <Suspense fallback={<NoteListSkeleton />}>
                <NoteList searchText={""/*searchText*/} />
              </Suspense>
            </nav>
          </section>
          <section key={1/*selectedId*/} className="col note-viewer">
            {children}
          </section>
        </div>
      </body>
    </html>
  )
}
